import { Component } from '@angular/core';

interface Employee {
  employeeCode: string;
  employeeName: string;
  birthDate: string;
  birthCity: string;
  employeeId: string;
  department: string;
  jobTitle: string;
  directManager: string;
  contractType: string;
  status: string;
}

@Component({
  selector: 'app-table-view',
  imports: [],
  templateUrl: './table-view.html',
  styleUrl: './table-view.css',
})
export class TableView {
  employees: Employee[] = [
    {
      employeeCode: 'EMP-001',
      employeeName: 'John Doe',
      birthDate: '1990-06-15',
      birthCity: 'Cairo',
      employeeId: 'ID-2024-001',
      department: 'Information Technology',
      jobTitle: 'Software Engineer',
      directManager: 'Jane Smith',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-002',
      employeeName: 'Sara Ali',
      birthDate: '1988-03-22',
      birthCity: 'Alexandria',
      employeeId: 'ID-2024-002',
      department: 'Human Resources',
      jobTitle: 'HR Specialist',
      directManager: 'Ahmed Hassan',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-004',
      employeeName: 'Nour Ibrahim',
      birthDate: '1993-07-30',
      birthCity: 'Luxor',
      employeeId: 'ID-2024-004',
      department: 'Marketing',
      jobTitle: 'Marketing Manager',
      directManager: 'John Doe',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-005',
      employeeName: 'Khaled Omar',
      birthDate: '1985-01-14',
      birthCity: 'Port Said',
      employeeId: 'ID-2024-005',
      department: 'Operations',
      jobTitle: 'Operations Lead',
      directManager: 'Jane Smith',
      contractType: 'Part-Time',
      status: 'Inactive',
    },
    {
      employeeCode: 'EMP-001',
      employeeName: 'John Doe',
      birthDate: '1990-06-15',
      birthCity: 'Cairo',
      employeeId: 'ID-2024-001',
      department: 'Information Technology',
      jobTitle: 'Software Engineer',
      directManager: 'Jane Smith',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-002',
      employeeName: 'Sara Ali',
      birthDate: '1988-03-22',
      birthCity: 'Alexandria',
      employeeId: 'ID-2024-002',
      department: 'Human Resources',
      jobTitle: 'HR Specialist',
      directManager: 'Ahmed Hassan',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-004',
      employeeName: 'Nour Ibrahim',
      birthDate: '1993-07-30',
      birthCity: 'Luxor',
      employeeId: 'ID-2024-004',
      department: 'Marketing',
      jobTitle: 'Marketing Manager',
      directManager: 'John Doe',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-005',
      employeeName: 'Khaled Omar',
      birthDate: '1985-01-14',
      birthCity: 'Port Said',
      employeeId: 'ID-2024-005',
      department: 'Operations',
      jobTitle: 'Operations Lead',
      directManager: 'Jane Smith',
      contractType: 'Part-Time',
      status: 'Inactive',
    },
    {
      employeeCode: 'EMP-001',
      employeeName: 'John Doe',
      birthDate: '1990-06-15',
      birthCity: 'Cairo',
      employeeId: 'ID-2024-001',
      department: 'Information Technology',
      jobTitle: 'Software Engineer',
      directManager: 'Jane Smith',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-002',
      employeeName: 'Sara Ali',
      birthDate: '1988-03-22',
      birthCity: 'Alexandria',
      employeeId: 'ID-2024-002',
      department: 'Human Resources',
      jobTitle: 'HR Specialist',
      directManager: 'Ahmed Hassan',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-004',
      employeeName: 'Nour Ibrahim',
      birthDate: '1993-07-30',
      birthCity: 'Luxor',
      employeeId: 'ID-2024-004',
      department: 'Marketing',
      jobTitle: 'Marketing Manager',
      directManager: 'John Doe',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-005',
      employeeName: 'Khaled Omar',
      birthDate: '1985-01-14',
      birthCity: 'Port Said',
      employeeId: 'ID-2024-005',
      department: 'Operations',
      jobTitle: 'Operations Lead',
      directManager: 'Jane Smith',
      contractType: 'Part-Time',
      status: 'Inactive',
    },
    {
      employeeCode: 'EMP-001',
      employeeName: 'John Doe',
      birthDate: '1990-06-15',
      birthCity: 'Cairo',
      employeeId: 'ID-2024-001',
      department: 'Information Technology',
      jobTitle: 'Software Engineer',
      directManager: 'Jane Smith',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-002',
      employeeName: 'Sara Ali',
      birthDate: '1988-03-22',
      birthCity: 'Alexandria',
      employeeId: 'ID-2024-002',
      department: 'Human Resources',
      jobTitle: 'HR Specialist',
      directManager: 'Ahmed Hassan',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-004',
      employeeName: 'Nour Ibrahim',
      birthDate: '1993-07-30',
      birthCity: 'Luxor',
      employeeId: 'ID-2024-004',
      department: 'Marketing',
      jobTitle: 'Marketing Manager',
      directManager: 'John Doe',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-005',
      employeeName: 'Khaled Omar',
      birthDate: '1985-01-14',
      birthCity: 'Port Said',
      employeeId: 'ID-2024-005',
      department: 'Operations',
      jobTitle: 'Operations Lead',
      directManager: 'Jane Smith',
      contractType: 'Part-Time',
      status: 'Inactive',
    },
    {
      employeeCode: 'EMP-001',
      employeeName: 'John Doe',
      birthDate: '1990-06-15',
      birthCity: 'Cairo',
      employeeId: 'ID-2024-001',
      department: 'Information Technology',
      jobTitle: 'Software Engineer',
      directManager: 'Jane Smith',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-002',
      employeeName: 'Sara Ali',
      birthDate: '1988-03-22',
      birthCity: 'Alexandria',
      employeeId: 'ID-2024-002',
      department: 'Human Resources',
      jobTitle: 'HR Specialist',
      directManager: 'Ahmed Hassan',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-004',
      employeeName: 'Nour Ibrahim',
      birthDate: '1993-07-30',
      birthCity: 'Luxor',
      employeeId: 'ID-2024-004',
      department: 'Marketing',
      jobTitle: 'Marketing Manager',
      directManager: 'John Doe',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-005',
      employeeName: 'Khaled Omar',
      birthDate: '1985-01-14',
      birthCity: 'Port Said',
      employeeId: 'ID-2024-005',
      department: 'Operations',
      jobTitle: 'Operations Lead',
      directManager: 'Jane Smith',
      contractType: 'Part-Time',
      status: 'Inactive',
    },
    {
      employeeCode: 'EMP-001',
      employeeName: 'John Doe',
      birthDate: '1990-06-15',
      birthCity: 'Cairo',
      employeeId: 'ID-2024-001',
      department: 'Information Technology',
      jobTitle: 'Software Engineer',
      directManager: 'Jane Smith',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-002',
      employeeName: 'Sara Ali',
      birthDate: '1988-03-22',
      birthCity: 'Alexandria',
      employeeId: 'ID-2024-002',
      department: 'Human Resources',
      jobTitle: 'HR Specialist',
      directManager: 'Ahmed Hassan',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-004',
      employeeName: 'Nour Ibrahim',
      birthDate: '1993-07-30',
      birthCity: 'Luxor',
      employeeId: 'ID-2024-004',
      department: 'Marketing',
      jobTitle: 'Marketing Manager',
      directManager: 'John Doe',
      contractType: 'Full-Time',
      status: 'Active',
    },
    {
      employeeCode: 'EMP-005',
      employeeName: 'Khaled Omar',
      birthDate: '1985-01-14',
      birthCity: 'Port Said',
      employeeId: 'ID-2024-005',
      department: 'Operations',
      jobTitle: 'Operations Lead',
      directManager: 'Jane Smith',
      contractType: 'Part-Time',
      status: 'Inactive',
    },
  ];

  getStatusClass(status: string): string {
    return status.toLowerCase().replace(' ', '-');
  }
}
